### ISSUE TITLE
Owin StartOptions ServerFactory 

### ISSUE THREAD

**Issue by TheAngryByrd** [SuaveIO/suave#353]
I was looking into switching out the webserver of an existing owin app for Suave's webserver.  I was hoping to be able to change the ServerFactory in the StartOptions like so:
```
            let port = 8085
            let options = StartOptions ()
            options.Port <- port |> Nullable<int>
            //options.ServerFactory <- "Nowin"
            options.ServerFactory <- "Suave.Owin"
            use app = WebApp.Start<OwinStartup.Startup>(options)
```  

However I get the following exception
```
System.MissingMethodException: Method 'ServerFactory.Create' not found.
  at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create (IAppBuilder builder) [0x00028] in <filename unknown>:0 
  at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer (Microsoft.Owin.Hosting.Engine.StartContext context) [0x0000c] in <filename unknown>:0 
  at Microsoft.Owin.Hosting.Engine.HostingEngine.Start (Microsoft.Owin.Hosting.Engine.StartContext context) [0x00065] in <filename unknown>:0 
  at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start (Microsoft.Owin.Hosting.StartOptions options) [0x0000c] in <filename unknown>:0 
  at Microsoft.Owin.Hosting.Starter.HostingStarter.Start (Microsoft.Owin.Hosting.StartOptions options) [0x0002e] in <filename unknown>:0 
  at Microsoft.Owin.Hosting.WebApp.StartImplementation (IServiceProvider services, Microsoft.Owin.Hosting.StartOptions options) [0x0004b] in <filename unknown>:0 
  at Microsoft.Owin.Hosting.WebApp.Start (Microsoft.Owin.Hosting.StartOptions options) [0x00014] in <filename unknown>:0 
  at Microsoft.Owin.Hosting.WebApp.Start[TStartup] (Microsoft.Owin.Hosting.StartOptions options) [0x00023] in <filename unknown>:0 
  at OwinFactorySwap.Console.Main.main (System.String[] argv) [0x0002b]
```
Should this be a supported use case?

I have an example app demonstrating the problem here: https://github.com/TheAngryByrd/OwinFactorySwap/blob/master/src/OwinFactorySwap.Console/Program.fs

//cc @panesofglass 

Thanks

**Comment by panesofglass** [comment]
@TheAngryByrd that's an interesting scenario. It's unfortunately not part of OWIN proper, so it's really up to Suave to determine whether or not to support that startup scenario.

**Comment by TheAngryByrd** [comment]
@haf Yeah there's a few examples of servers using ServerFactory in that way:  
* https://github.com/Bobris/Nowin/blob/master/OwinHostingSample/Program.cs 
* https://github.com/unosquare/embedio-extras/blob/72d5514be65c219b898808cc222d429a9b4aba4f/Unosquare.Labs.EmbedIO.ExtraTests/EmbedioOwinTest.cs


I did try as you suggested:
```
options.ServerFactory <- "Suave.Owin+OwinServerFactory"
``` 
but now it seems to be blocking.

I created a small C# wrapper class to help debug
```
options.ServerFactory <- "OwinFactorySwap.Lib"
```
```
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Suave;

namespace OwinFactorySwap.Lib
{
	public static class OwinServerFactory
	{
		public static void Initialize(IDictionary<string, object> properties)
		{
			Suave.Owin.OwinServerFactory.Initialize(properties);
		}
		public static IDisposable Create(Func<IDictionary<string, object>, Task> app, IDictionary<string, object> properties)
		{
			var x = Suave.Owin.OwinServerFactory.Create(app, properties);
			return x;
		}
	}
}

```

And it seems to be blocking on ```Suave.Owin.OwinServerFactory.Create```.


@panesofglass It does seem to be a bit of magic, having to implement OwinServerFactory and know the namespace in which it resides.  Would it be recommended to not go about it this way?

**Comment by haf** [comment]
The above behaviour is completely untested; would be a really great PR if you expand on what's there!

**Comment by TheAngryByrd** [comment]
I have a hunch that it may be related to https://github.com/SuaveIO/suave/blob/master/src/Suave/Owin.fs#L849 never finishing.

**Comment by haf** [comment]
Yes, do a `Async.Start listening` before that line.

**Comment by TheAngryByrd** [comment]
And yet again, we get a little farther.   The server now starts up.
```
[I] 2015-12-09T21:14:03.5517480Z: listener started in 76.522 ms with binding 127.0.0.1:8080 [Suave.Tcp.tcpIpServer]
```
But, when I hit the root:

```
[W] 2015-12-09T21:14:13.6585410Z: tcp request processing failed [Suave.Tcp.job] exn:
System.ObjectDisposedException: Cannot access a closed Stream.
  at System.IO.__Error.StreamIsClosed () [0x00000] in /private/tmp/source-mono-mac-4.2.0-branch/bockbuild-mono-4.2.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.2.1/external/referencesource/mscorlib/system/io/__error.cs:44 
  at System.IO.MemoryStream.Seek (Int64 offset, SeekOrigin loc) [0x0000b] in /private/tmp/source-mono-mac-4.2.0-branch/bockbuild-mono-4.2.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.2.1/external/referencesource/mscorlib/system/io/memorystream.cs:515 
  at Suave.Utils.OpenStream`1[T].Seek (Int64 offset, SeekOrigin dir) [0x00000] in /Documents/GitHub/suave/src/Suave/Utils/OpenMemoryStream.fs:75 
  at Suave.Owin+OwinAppModule+setResponseData@657.Invoke (Suave.Utils.OpenMemoryStream ms) [0x00000] in /Documents/GitHub/suave/src/Suave/Owin.fs:657 
  at Suave.Owin+OwinAppModule+OwinDictionary.Finalise () [0x000ff] in /Documents/GitHub/suave/src/Suave/Owin.fs:662 
  at Suave.Owin+OwinAppModule+impl@755-4.Invoke (Microsoft.FSharp.Core.Unit _arg2) [0x00014] in /Documents/GitHub/suave/src/Suave/Owin.fs:756 
  at <StartupCode$Suave>.$SocketMonad+Bind@16-1[a,b].Invoke (Microsoft.FSharp.Core.FSharpChoice`2 _arg1) [0x0001d] in /Documents/GitHub/suave/src/Suave/Sockets/SocketMonad.fs:17 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+args@835-1[a,b].Invoke (a a) [0x00000] in /private/tmp/source-mono-mac-4.2.0-branch/bockbuild-mono-4.2.0-branch/profiles/mono-mac-xamarin/build-root/fsharp-fsharp-14db8f5/src/fsharp/FSharp.Core/control.fs:835 
```

Any ideas off the top of your head?

**Comment by haf** [comment]
The next step is to enable verbose logging to see the interaction with Owin, but it would seem that the data is written either in pieces or twice in the particular app you're using.

**Comment by panesofglass** [comment]
@TheAngryByrd I think it's certainly to Suave's benefit to support the Katana (Microsoft.Owin) hosting mechanisms, as that will then expand their reach.

**Comment by haf** [comment]
For the above error, if you have a small repro I can fix it =)

**Comment by TheAngryByrd** [comment]
I'll just send the PR as a WIP.

**Comment by TheAngryByrd** [comment]
@haf I did put an example in #354.  Just pinging to see if you need anything else.

**Comment by haf** [comment]
@TheAngryByrd Thank you. Just the verbose logs then. What I really need it more time/money to buy time to have a look at this. Will try this weekend? I'm currently stuck at finishing Logary v4 for works https://github.com/logary/logary/pull/92

**Comment by TheAngryByrd** [comment]
No problem!  I'll start poking around myself. If you have any more hints I'd gladly appreciate it. 

Verbose:
```
[V] 2015-12-11T10:22:20.9356958Z: initialising BufferManager with 827392 bytes [
Suave.Socket.BufferManager]
[I] 2015-12-11T10:22:20.9706919Z: listener started in 84.012 ms with binding 127
.0.0.1:8080 [Suave.Tcp.tcpIpServer]
Server started on port 8080
[V] 2015-12-11T10:22:28.8603239Z: 127.0.0.1 connected, total: 1 clients [Suave.T
cp.job]
[V] 2015-12-11T10:22:28.8633251Z: reserving buffer: 811008, free count: 99 [Suav
e.Tcp.job] [Suave.Socket.BufferManager]
[V] 2015-12-11T10:22:28.8693247Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-12-11T10:22:28.8703242Z: reading first line of request [Suave.Web.proce
ssRequest]
[V] 2015-12-11T10:22:28.8853223Z: reserving buffer: 802816, free count: 98 [Suav
e.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-12-11T10:22:28.9023238Z: reading headers [Suave.Web.processRequest]
[V] 2015-12-11T10:22:28.9068331Z: freeing buffer: 802816, free count: 99 [Suave.
Web.split] [Suave.Socket.BufferManager]
[V] 2015-12-11T10:22:28.9173333Z: parsing post data [Suave.Web.processRequest]
[V] 2015-12-11T10:22:28.9198331Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-12-11T10:22:28.9983360Z: yielding to OWIN middleware [Suave.Owin]
[V] 2015-12-11T10:22:29.1585534Z: suave back in control [Suave.Owin]
[W] 2015-12-11T10:22:42.1325944Z: tcp request processing failed [Suave.Tcp.job]
exn:
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at Suave.Utils.OpenStream`1.Seek(Int64 offset, SeekOrigin dir) in C:\Users\ji
mmy_000\Documents\GitHub\suave\src\Suave\Utils\OpenMemoryStream.fs:line 75
   at Suave.Owin.OwinAppModule.setResponseData@657.Invoke(OpenMemoryStream ms) i
n C:\Users\jimmy_000\Documents\GitHub\suave\src\Suave\Owin.fs:line 657
   at Suave.Owin.OwinAppModule.OwinDictionary.Finalise() in C:\Users\jimmy_000\D
ocuments\GitHub\suave\src\Suave\Owin.fs:line 662
   at Suave.Owin.OwinAppModule.impl@755-4.Invoke(Unit _arg2) in C:\Users\jimmy_0
00\Documents\GitHub\suave\src\Suave\Owin.fs:line 756
   at <StartupCode$Suave>.$SocketMonad.Bind@16-1.Invoke(FSharpChoice`2 _arg1) in
 C:\Users\jimmy_000\Documents\GitHub\suave\src\Suave\Sockets\SocketMonad.fs:line
 17
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
[V] 2015-12-11T10:22:42.1464936Z: freeing buffer: 811008, free count: 100 [Suave
.Tcp.job] [Suave.Socket.BufferManager]
[V] 2015-12-11T10:22:42.1474926Z: Shutting down transport. [Suave.Tcp.job]
[V] 2015-12-11T10:22:42.1514981Z: 127.0.0.1 disconnected, total: 0 clients [Suav
e.Tcp.job]

```


Thanks!

**Comment by TheAngryByrd** [comment]
It ends up blowing up at:
https://github.com/SuaveIO/suave/blob/master/src/Suave/Owin.fs#L665

So it seems the responseStream is being disposed before we can write to it:
https://github.com/SuaveIO/suave/blob/master/src/Suave/Owin.fs#L720

It seems to be getting disposed after: 
https://github.com/SuaveIO/suave/blob/master/src/Suave/Owin.fs#L777

Commenting out the dispose to responseStream yields the correct hello world response however I don't think that is a real solution :)

**Comment by TheAngryByrd** [comment]
Seems like when Nancy disposes it's NancyContext it also disposes the OwinDictionary.
```
>	Suave.dll!Suave.Owin.OwinAppModule.OwinDictionary.System.IDisposable.System-IDisposable-Dispose() Line 720	F#
 	Nancy.dll!Nancy.NancyContext.Dispose()	Unknown
 	Nancy.dll!Nancy.Owin.NancyMiddleware.RequestComplete.AnonymousMethod__a(Nancy.NancyContext context)	Unknown
 	Nancy.dll!Nancy.NancyEngineExtensions.HandleRequest(Nancy.INancyEngine nancyEngine, Nancy.Request request, System.Func<Nancy.NancyContext, Nancy.NancyContext> preRequest, System.Action<Nancy.NancyContext> onComplete, System.Action<System.Exception> onError, System.Threading.CancellationToken cancellationToken)	Unknown
 	Nancy.dll!Nancy.Owin.NancyMiddleware.UseNancy.AnonymousMethod__1(System.Collections.Generic.IDictionary<string, object> environment)	Unknown
 	Microsoft.Owin.Hosting.dll!Microsoft.Owin.Hosting.Utilities.Encapsulate.Invoke(System.Collections.Generic.IDictionary<string, object> environment)	Unknown
 	Suave.dll!Suave.Owin.OwinAppModule.OfAppFunc@778.Invoke(System.Collections.Generic.IDictionary<string, object> e) Line 778	F#

```

**Comment by TheAngryByrd** [comment]
I seem to be getting the same issue on the other NancyFx example projects.

**Comment by haf** [comment]
Nice work.

So

https://github.com/NancyFx/Nancy/blob/master/src/Nancy/NancyContext.cs#L124

Disposes the context which disposes the memory buffer. I'm not quite sure that the OWIN app should be disposing the stream, because it's not its responsibility...

I suppose you could OwinContext from Suave to "know" from where Dispose is being called, or remove it from the dictionary entries.

**Comment by haf** [comment]
Strange you get it on the samples, they worked for me when I wrote them. Something must have changed.

**Comment by TheAngryByrd** [comment]
I can only guess, but might have something to do with the stream implementation changing:
https://github.com/SuaveIO/suave/commit/530e5f90506e6fc2e965d3a0bccd01cb1ee2eef9#diff-b41f275d6cdfe9f95ef8dd4c3cf71946L575

**Comment by haf** [comment]
This should have been fixed with v1. If it hasn't been, please notify us.
