### ISSUE TITLE
System.Net.Sockets.SocketException: The attempted operation is not supported for the type of object referenced

### ISSUE THREAD

**Issue by chinwobble** [SuaveIO/suave#572]
I receive the following exception when attempting to run Suave as a service in topshelf on Windows Server 2008.

```
D 2017-01-24T04:53:40.7329649+00:00: Object connected. Now has 1 connected [Suave.Tcp]
  client => 
    Address => 16777343
    AddressFamily => 
    IsIPv4MappedToIPv6 => False
    IsIPv6LinkLocal => False
    IsIPv6Multicast => False
    IsIPv6SiteLocal => False
    IsIPv6Teredo => False
    ScopeId => "Property accessor ScopeId on System.Net.IPAddress threw an exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Sockets.SocketException: The attempted operation is not supported for the type of object referenced
   at System.Net.IPAddress.get_ScopeId()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Logary.Internals.Map.f@1-1(Object data, PropertyInfo pi)"
  totalClients => 1
```

My config is as follows in Suave 2.0.2:
```
let start hc =
        let cts = new CancellationTokenSource()
        let token = cts.Token
        let config = 
            { defaultConfig with 
                bindings = [ HttpBinding.createSimple HTTP "127.0.0.1" 8081 ]
                cancellationToken = token
                logger = LoggerAdapter.createGeneric logger}
        startWebServerAsync config app
        |> snd
        |> Async.StartAsTask
        |> ignore
        cancellationTokenSource := Some cts
        true
```

I tried to search for a solution and came across this: https://social.msdn.microsoft.com/Forums/en-US/45df4dce-e6dc-4dac-8a6e-036727a33919/socket-exception-the-attempted-operation-is-not-supported-for-the-type-of-object-referenced?forum=netfxnetcom
My scenario seems very similar, I can go to the browser and get a good response from the server, but when I try to make an api call programmatic (lua script) I get the exception when the Suave app attempts to make its own api call to another web service (asynchronously).
The suggested in solution is to change the calls to synchronous method which doesn't seem right. 

Have any others encountered this issue? I'm using .NET Framework 4.6.

**Comment by adamchester** [comment]
Might be related to https://github.com/logary/logary/issues/228

**Comment by adamchester** [comment]
The source logging statement in Suave is [here](https://github.com/SuaveIO/suave/blob/f53739ac9914783f0f7d2227c757468247f50934/src/Suave/Tcp.fs#L102). It adds the `{client}` field as a value of type `System.Net.IPAddress`. Later, when processing the log message, Logary attempts to enumerate all the public properties of this IP Address, and `ScopeId` throws an exception.

Thinking out loud: one solution is for Suave to stop logging this object type, log an object that can be serialised better. Another option is for Logary to be smarter about how it processes values of type `System.Net.IPAddress`.

**Comment by chinwobble** [comment]
@adamchester thanks for investigating this. I guess as a workaround we could the client application of suave logary set the log level to info to prevent the debug logging from being executed?

**Comment by adamchester** [comment]
@chinwobble yes it's unlikely you want Suave to use debug level all the time, turning it off would work around this small issue.

**Comment by chinwobble** [comment]
@adamchester can you show some code on how to do this?

**Comment by adamchester** [comment]
@chinwobble assuming you are using Logary, create a rule that will set the minimal level to >= Info like this https://github.com/logary/logary#rule--hierarchical-logging

**Comment by endeavour** [comment]
I am still seeing this issue with 2.0.3

**Comment by adamchester** [comment]
@endeavour can you provide any further details please? How are seeing this issue? what versions of software are you using? what does the log message(s) look like?

**Comment by endeavour** [comment]
Hi Adam, thanks for the response. 

The error looks like this:

```
I 2017-02-17T17:05:48.7495859+00:00: Smooth! Suave listener started in 31.2523 with binding 127.0.0.1:8083 [Suave.Tcp.runServer]
  ipAddress => "127.0.0.1"
  port => 8083
  startedListeningMilliseconds => 31.2523
D 2017-02-17T17:05:48.8227644+00:00: Initialising BufferManager with 827392 [Suave.Sockets.BufferManager]
  totalBytes => 827392
D 2017-02-17T17:05:55.3432152+00:00: 127.0.0.1 connected. Now has 1 connected [Suave.Tcp]
  client => "127.0.0.1"
  totalClients => 1
D 2017-02-17T17:05:55.5852942+00:00: 127.0.0.1 connected. Now has 2 connected [Suave.Tcp]
  client => "127.0.0.1"
  totalClients => 2
D 2017-02-17T17:05:55.8540139+00:00: Shutting down transport [Suave.Tcp]
D 2017-02-17T17:05:55.8620162+00:00: Disconnected Object. 1 connected. [Suave.Tcp]
  client => 
    Address => 16777343
    AddressFamily => 
    IsIPv4MappedToIPv6 => False
    IsIPv6LinkLocal => False
    IsIPv6Multicast => False
    IsIPv6SiteLocal => False
    IsIPv6Teredo => False
    ScopeId => "Property accessor ScopeId on System.Net.IPAddress threw an exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Sockets.SocketException: The attempted operation is not supported for the type of object referenced
   at System.Net.IPAddress.get_ScopeId()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Logary.Internals.Map.f@1-1(Object data, PropertyInfo pi)"
  totalClients => 1
D 2017-02-17T17:06:20.6329977+00:00: Shutting down transport [Suave.Tcp]
D 2017-02-17T17:06:20.6339979+00:00: Disconnected Object. 0 connected. [Suave.Tcp]
  client => 
    Address => 16777343
    AddressFamily => 
    IsIPv4MappedToIPv6 => False
    IsIPv6LinkLocal => False
    IsIPv6Multicast => False
    IsIPv6SiteLocal => False
    IsIPv6Teredo => False
    ScopeId => "Property accessor ScopeId on System.Net.IPAddress threw an exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Sockets.SocketException: The attempted operation is not supported for the type of object referenced
   at System.Net.IPAddress.get_ScopeId()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Logary.Internals.Map.f@1-1(Object data, PropertyInfo pi)"
  totalClients => 0

```

The set up looks like this:

 ```
     // Configure logging
      let logary =
        withLogaryManager loggerName (
          withTargets [
            Console.create Console.empty "console"
            Debugger.create Debugger.empty "debugger"
            File.create fileLogConfig "file"
          ] >>
            withRules [
              { Rule.createForTarget "console" with level = LogLevel.Debug } 
              { Rule.createForTarget "debugger" with level = LogLevel.Debug } 
              { Rule.createForTarget "file" with level = LogLevel.Debug } 
            ]
          )
        |> Hopac.Hopac.run
      
      let logger = logary.getLogger (PointName.ofSingle loggerName)

      let config =
        defaultConfig.withLogger(LoggerAdapter.createGeneric logger)      
```

Versions (from paket.lock)
Suave 2.0.3
FSharp.Core 4.0.0.1
Logary 4.0.311
Logary.Adapters.Facade 4.0.311

**Comment by haf** [comment]
Need to find every logged `IPAddress` and do `ToString` on it.

**Comment by ademar** [comment]
Yeah here https://github.com/SuaveIO/suave/blob/master/src/Suave/Tcp.fs#L133
