### ISSUE TITLE
Unhandled Exception: System.Net.Sockets.SocketException: Address already in use

### ISSUE THREAD

**Issue by sporto** [SuaveIO/suave#682]
I'm trying Suave 2.2.1 with dotnet core 2.1.3 on Mac.

When I run `dotnet run` it builds ok. But then if I ctrl-c and run `dotnet run` again I get

```
Unhandled Exception: System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Suave.Tcp.runServer@148-3.Invoke(Unit unitVar0)
   at Suave.Tcp.run@85[a](FSharpFunc`2 f, UInt16 _arg1)
   at Suave.Tcp.run@85[a](FSharpFunc`2 f, UInt16 _arg1)
   at Suave.Tcp.runServer@143-2.Invoke(Socket _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
```

I have to wait a few secs and try again. So it seems that Suave or something else take a few seconds to unbind from the port.

If using `dotnet watch` (https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch)
I get the error on every application change.

**Comment by ademar** [comment]
Can you try the latest release v2.3.0-beta3 ?

**Comment by sporto** [comment]
Just tried v2.3.0-beta3. This version fixes this issue. Thanks.
